// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using device_manager_api.Infrastructure.Data;

#nullable disable

namespace device_manager_api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260121034641_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("device_manager_api.Domain.Entities.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea")
                        .HasDefaultValue(new byte[] { 0, 0, 0, 0, 0, 0, 0, 1 });

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Brand");

                    b.HasIndex("State");

                    b.HasIndex("Brand", "State");

                    b.ToTable("devices", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-000000000001"),
                            Brand = "Apple",
                            CreatedBy = "system",
                            CreationTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Laptop 001",
                            RowVersion = new byte[] { 0, 0, 0, 0, 0, 0, 0, 1 },
                            State = 0
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-000000000002"),
                            Brand = "Samsung",
                            CreatedBy = "system",
                            CreationTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Smartphone 002",
                            RowVersion = new byte[] { 0, 0, 0, 0, 0, 0, 0, 1 },
                            State = 0
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-000000000003"),
                            Brand = "Dell",
                            CreatedBy = "system",
                            CreationTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Tablet 003",
                            RowVersion = new byte[] { 0, 0, 0, 0, 0, 0, 0, 1 },
                            State = 0
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-000000000004"),
                            Brand = "HP",
                            CreatedBy = "system",
                            CreationTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Desktop 004",
                            RowVersion = new byte[] { 0, 0, 0, 0, 0, 0, 0, 1 },
                            State = 0
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-000000000005"),
                            Brand = "Lenovo",
                            CreatedBy = "system",
                            CreationTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Monitor 005",
                            RowVersion = new byte[] { 0, 0, 0, 0, 0, 0, 0, 1 },
                            State = 0
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-000000000006"),
                            Brand = "Sony",
                            CreatedBy = "system",
                            CreationTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Printer 006",
                            RowVersion = new byte[] { 0, 0, 0, 0, 0, 0, 0, 1 },
                            State = 0
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-000000000007"),
                            Brand = "LG",
                            CreatedBy = "system",
                            CreationTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Scanner 007",
                            RowVersion = new byte[] { 0, 0, 0, 0, 0, 0, 0, 1 },
                            State = 0
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-000000000008"),
                            Brand = "Microsoft",
                            CreatedBy = "system",
                            CreationTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Router 008",
                            RowVersion = new byte[] { 0, 0, 0, 0, 0, 0, 0, 1 },
                            State = 0
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-000000000009"),
                            Brand = "Google",
                            CreatedBy = "system",
                            CreationTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Server 009",
                            RowVersion = new byte[] { 0, 0, 0, 0, 0, 0, 0, 1 },
                            State = 0
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-000000000010"),
                            Brand = "Asus",
                            CreatedBy = "system",
                            CreationTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Smartwatch 010",
                            RowVersion = new byte[] { 0, 0, 0, 0, 0, 0, 0, 1 },
                            State = 0
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-000000000011"),
                            Brand = "Apple",
                            CreatedBy = "system",
                            CreationTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Laptop 011",
                            RowVersion = new byte[] { 0, 0, 0, 0, 0, 0, 0, 1 },
                            State = 0
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-000000000012"),
                            Brand = "Samsung",
                            CreatedBy = "system",
                            CreationTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Smartphone 012",
                            RowVersion = new byte[] { 0, 0, 0, 0, 0, 0, 0, 1 },
                            State = 0
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-000000000013"),
                            Brand = "Dell",
                            CreatedBy = "system",
                            CreationTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Tablet 013",
                            RowVersion = new byte[] { 0, 0, 0, 0, 0, 0, 0, 1 },
                            State = 0
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-000000000014"),
                            Brand = "HP",
                            CreatedBy = "system",
                            CreationTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Desktop 014",
                            RowVersion = new byte[] { 0, 0, 0, 0, 0, 0, 0, 1 },
                            State = 0
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-000000000015"),
                            Brand = "Lenovo",
                            CreatedBy = "system",
                            CreationTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Monitor 015",
                            RowVersion = new byte[] { 0, 0, 0, 0, 0, 0, 0, 1 },
                            State = 0
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-000000000016"),
                            Brand = "Sony",
                            CreatedBy = "system",
                            CreationTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Printer 016",
                            RowVersion = new byte[] { 0, 0, 0, 0, 0, 0, 0, 1 },
                            State = 0
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-000000000017"),
                            Brand = "LG",
                            CreatedBy = "system",
                            CreationTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Scanner 017",
                            RowVersion = new byte[] { 0, 0, 0, 0, 0, 0, 0, 1 },
                            State = 0
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-000000000018"),
                            Brand = "Microsoft",
                            CreatedBy = "system",
                            CreationTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Router 018",
                            RowVersion = new byte[] { 0, 0, 0, 0, 0, 0, 0, 1 },
                            State = 0
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-000000000019"),
                            Brand = "Google",
                            CreatedBy = "system",
                            CreationTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Server 019",
                            RowVersion = new byte[] { 0, 0, 0, 0, 0, 0, 0, 1 },
                            State = 0
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-000000000020"),
                            Brand = "Asus",
                            CreatedBy = "system",
                            CreationTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Smartwatch 020",
                            RowVersion = new byte[] { 0, 0, 0, 0, 0, 0, 0, 1 },
                            State = 0
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-000000000021"),
                            Brand = "Apple",
                            CreatedBy = "system",
                            CreationTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Laptop 021",
                            RowVersion = new byte[] { 0, 0, 0, 0, 0, 0, 0, 1 },
                            State = 0
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-000000000022"),
                            Brand = "Samsung",
                            CreatedBy = "system",
                            CreationTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Smartphone 022",
                            RowVersion = new byte[] { 0, 0, 0, 0, 0, 0, 0, 1 },
                            State = 0
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-000000000023"),
                            Brand = "Dell",
                            CreatedBy = "system",
                            CreationTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Tablet 023",
                            RowVersion = new byte[] { 0, 0, 0, 0, 0, 0, 0, 1 },
                            State = 0
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-000000000024"),
                            Brand = "HP",
                            CreatedBy = "system",
                            CreationTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Desktop 024",
                            RowVersion = new byte[] { 0, 0, 0, 0, 0, 0, 0, 1 },
                            State = 0
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-000000000025"),
                            Brand = "Lenovo",
                            CreatedBy = "system",
                            CreationTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Monitor 025",
                            RowVersion = new byte[] { 0, 0, 0, 0, 0, 0, 0, 1 },
                            State = 0
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-000000000026"),
                            Brand = "Sony",
                            CreatedBy = "system",
                            CreationTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Printer 026",
                            RowVersion = new byte[] { 0, 0, 0, 0, 0, 0, 0, 1 },
                            State = 0
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-000000000027"),
                            Brand = "LG",
                            CreatedBy = "system",
                            CreationTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Scanner 027",
                            RowVersion = new byte[] { 0, 0, 0, 0, 0, 0, 0, 1 },
                            State = 0
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-000000000028"),
                            Brand = "Microsoft",
                            CreatedBy = "system",
                            CreationTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Router 028",
                            RowVersion = new byte[] { 0, 0, 0, 0, 0, 0, 0, 1 },
                            State = 0
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-000000000029"),
                            Brand = "Google",
                            CreatedBy = "system",
                            CreationTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Server 029",
                            RowVersion = new byte[] { 0, 0, 0, 0, 0, 0, 0, 1 },
                            State = 0
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-000000000030"),
                            Brand = "Asus",
                            CreatedBy = "system",
                            CreationTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Smartwatch 030",
                            RowVersion = new byte[] { 0, 0, 0, 0, 0, 0, 0, 1 },
                            State = 0
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-000000000031"),
                            Brand = "Apple",
                            CreatedBy = "system",
                            CreationTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Laptop 031",
                            RowVersion = new byte[] { 0, 0, 0, 0, 0, 0, 0, 1 },
                            State = 1
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-000000000032"),
                            Brand = "Samsung",
                            CreatedBy = "system",
                            CreationTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Smartphone 032",
                            RowVersion = new byte[] { 0, 0, 0, 0, 0, 0, 0, 1 },
                            State = 1
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-000000000033"),
                            Brand = "Dell",
                            CreatedBy = "system",
                            CreationTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Tablet 033",
                            RowVersion = new byte[] { 0, 0, 0, 0, 0, 0, 0, 1 },
                            State = 1
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-000000000034"),
                            Brand = "HP",
                            CreatedBy = "system",
                            CreationTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Desktop 034",
                            RowVersion = new byte[] { 0, 0, 0, 0, 0, 0, 0, 1 },
                            State = 1
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-000000000035"),
                            Brand = "Lenovo",
                            CreatedBy = "system",
                            CreationTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Monitor 035",
                            RowVersion = new byte[] { 0, 0, 0, 0, 0, 0, 0, 1 },
                            State = 1
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-000000000036"),
                            Brand = "Sony",
                            CreatedBy = "system",
                            CreationTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Printer 036",
                            RowVersion = new byte[] { 0, 0, 0, 0, 0, 0, 0, 1 },
                            State = 1
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-000000000037"),
                            Brand = "LG",
                            CreatedBy = "system",
                            CreationTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Scanner 037",
                            RowVersion = new byte[] { 0, 0, 0, 0, 0, 0, 0, 1 },
                            State = 1
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-000000000038"),
                            Brand = "Microsoft",
                            CreatedBy = "system",
                            CreationTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Router 038",
                            RowVersion = new byte[] { 0, 0, 0, 0, 0, 0, 0, 1 },
                            State = 1
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-000000000039"),
                            Brand = "Google",
                            CreatedBy = "system",
                            CreationTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Server 039",
                            RowVersion = new byte[] { 0, 0, 0, 0, 0, 0, 0, 1 },
                            State = 1
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-000000000040"),
                            Brand = "Asus",
                            CreatedBy = "system",
                            CreationTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Smartwatch 040",
                            RowVersion = new byte[] { 0, 0, 0, 0, 0, 0, 0, 1 },
                            State = 1
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-000000000041"),
                            Brand = "Apple",
                            CreatedBy = "system",
                            CreationTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Laptop 041",
                            RowVersion = new byte[] { 0, 0, 0, 0, 0, 0, 0, 1 },
                            State = 1
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-000000000042"),
                            Brand = "Samsung",
                            CreatedBy = "system",
                            CreationTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Smartphone 042",
                            RowVersion = new byte[] { 0, 0, 0, 0, 0, 0, 0, 1 },
                            State = 1
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-000000000043"),
                            Brand = "Dell",
                            CreatedBy = "system",
                            CreationTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Tablet 043",
                            RowVersion = new byte[] { 0, 0, 0, 0, 0, 0, 0, 1 },
                            State = 1
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-000000000044"),
                            Brand = "HP",
                            CreatedBy = "system",
                            CreationTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Desktop 044",
                            RowVersion = new byte[] { 0, 0, 0, 0, 0, 0, 0, 1 },
                            State = 1
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-000000000045"),
                            Brand = "Lenovo",
                            CreatedBy = "system",
                            CreationTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Monitor 045",
                            RowVersion = new byte[] { 0, 0, 0, 0, 0, 0, 0, 1 },
                            State = 1
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-000000000046"),
                            Brand = "Sony",
                            CreatedBy = "system",
                            CreationTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Printer 046",
                            RowVersion = new byte[] { 0, 0, 0, 0, 0, 0, 0, 1 },
                            State = 2
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-000000000047"),
                            Brand = "LG",
                            CreatedBy = "system",
                            CreationTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Scanner 047",
                            RowVersion = new byte[] { 0, 0, 0, 0, 0, 0, 0, 1 },
                            State = 2
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-000000000048"),
                            Brand = "Microsoft",
                            CreatedBy = "system",
                            CreationTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Router 048",
                            RowVersion = new byte[] { 0, 0, 0, 0, 0, 0, 0, 1 },
                            State = 2
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-000000000049"),
                            Brand = "Google",
                            CreatedBy = "system",
                            CreationTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Server 049",
                            RowVersion = new byte[] { 0, 0, 0, 0, 0, 0, 0, 1 },
                            State = 2
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-000000000050"),
                            Brand = "Asus",
                            CreatedBy = "system",
                            CreationTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Smartwatch 050",
                            RowVersion = new byte[] { 0, 0, 0, 0, 0, 0, 0, 1 },
                            State = 2
                        });
                });

            modelBuilder.Entity("device_manager_api.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            PasswordHash = "$2a$12$yc7jeLROf1Gv/PpQbqQkgOnnOKWbHJZt17fcNZrbM5TkDFOiVtJta",
                            Role = 0,
                            Username = "admin1"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111112"),
                            PasswordHash = "$2a$12$IgdRp/rI37ALjB7qsKAu8Oo70B8ZM7GX1g.r031nJ96fJazRuLhPO",
                            Role = 0,
                            Username = "admin2"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222221"),
                            PasswordHash = "$2a$12$9KedhTiOP/MuS/9OVjTXmeV8.4WjfiGT4JO3qhFHNBlI/JaoqBbwa",
                            Role = 1,
                            Username = "manager1"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            PasswordHash = "$$2a$12$I1fLhtp9vplrLTNKEADFOO85IaQFg0nLyeoUUqPAGHTELD5/96Iii",
                            Role = 1,
                            Username = "manager2"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333331"),
                            PasswordHash = "$2a$12$iHTaa1AYo6r2hJVJY876JeUzGQTf8tjFf32jSybFbbf7S6vaayGui",
                            Role = 2,
                            Username = "viewer1"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333332"),
                            PasswordHash = "$2a$12$J.8.n1hf.KXKf8FcOGVSI.r5DFmD.ykbTSsqHMvTKGvGVEw.uI8Dy",
                            Role = 2,
                            Username = "viewer2"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
